### ISSUE TITLE
Compile the jpgs into Pdf or Cbz

### ISSUE THREAD

**Issue by fossimprove** [Sidmaz666/manga#1]
Hey, firstly i love the way you went with fzf / rofi. Its fantastic.

Rather than having lots of jpgs on storage, its better to have them in pdf or cbz and remove those jpgs.

Pdf can be done by convert command
Cbz by zip command.

Its small script that works great!
Thank you!

**Comment by Sidmaz666** [comment]
> Hey, firstly i love the way you went with fzf / rofi. Its fantastic.
> 
> Rather than having lots of jpgs on storage, its better to have them in pdf or cbz and remove those jpgs.
> 
> Pdf can be done by convert command Cbz by zip command.
> 
> Its small script that works great! Thank you!

Thank you very much for a review and thanks for the idea of compiling jpges into pdf that would be great 🤩  currently I can't work on anything so i will do a brief research on this topic and will find a satisfying solution, i think imagemagick can do it.

**Comment by fossimprove** [comment]
You can refer this commit from another similar Manga-cli script
https://github.com/notprash/manga-cli/commit/ad7880457be9a9c020ca4ad680e4fab6b340a4b1

`zip -q $HOME/Document/Manga$F_TITLE/$CH_DIR.cbz $HOME/Document/Manga/$F_TITLE/$CH_DIR/P*.jpg`

This could do to cbz

`convert P*jpg ch.pdf`

this could do for pdf

**Comment by Sidmaz666** [comment]
Closing this issue because I have added the functionality on the latest [commit](https://github.com/Sidmaz666/manga/commit/7856a6761b37ba72bb4eb0fc14fdaeace6743441) !
