### ISSUE TITLE
Unknown option: --header-first

### ISSUE THREAD

**Issue by afisarsy** [Sidmaz666/manga#3]
Can't search any manga, Just tried using
```bash
manga Saki
```

and got  this
```bash
unknown option: --header-first
```

I use Debian WSL and already installed all the dependencies

**Comment by Sidmaz666** [comment]
The error  `unknown option: --header-first` is a fzf error maybe the windows version of fzf does not support the parameter, ensure you install the latest version of fzf that supports the --header-first parameter, or you could just open the script and remove the --header-first parammeter, it has it's disadvantage. Lastly, ensure that the script is able to call fzf and other dependencies from the /bin folder of your Debian WSL.

**Comment by afisarsy** [comment]
Just checked my fzf and realized that I was using fzf 0.24, and ```--header-first``` option only available on fzf 0.28 or later.
